#!/usr/bin/env python3
"""Generate (or verify) SDK_MAP.md from the public surface of the three SDK modules.

The map is generated output: everything between the AUTOGEN markers is rebuilt
from source on every run. Prose outside those markers is preserved verbatim, so
hand-written analysis survives regeneration.

Usage:
    generate_sdk_map.py            # rewrite SDK_MAP.md in place
    generate_sdk_map.py --check    # exit 1 if the map is out of date (no write)
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAP_PATH = os.path.join(REPO_ROOT, "SDK_MAP.md")

MODULES = ["FrameSDK", "FrameSDK-UI", "FrameSDK-Onboarding"]

BEGIN = "<!-- BEGIN AUTOGENERATED SDK MAP -->"
END = "<!-- END AUTOGENERATED SDK MAP -->"

# Kotlin declarations are public by default: there is no `public` keyword to
# match on (unlike Swift's opt-in model). The two access modifiers that hide a
# declaration from callers outside the module/file are `internal` and
# `private`. `protected` only applies to members of open/abstract classes and
# is still not part of the public surface (a subclass, not an integrator, can
# reach it), so it counts as non-public here too.
NON_PUBLIC_MODS = {"private", "internal", "protected"}

# Declaration modifiers that may appear between the (optional) access modifier
# and the keyword.
_MODS = (
    r"(?:final|open|abstract|sealed|data|enum|annotation|inner|inline|"
    r"noinline|crossinline|suspend|tailrec|operator|infix|external|expect|"
    r"actual|override|lateinit|const|vararg|reified|out|in|value|fun)"
)

DECL_RE = re.compile(
    rf"^(?P<indent>[ \t]*)"
    rf"(?:(?:@\w+(?:\([^)]*\))?\s+)*)"          # leading annotations on the same line
    rf"(?:(?P<access>private|internal|protected|public)\s+)?"
    rf"(?P<mods>(?:{_MODS}\s+)*)"
    rf"(?P<kind>class|interface|object|fun|val|var|typealias)\b"
    rf"(?P<rest>.*)$"
)

# `enum class` / `sealed class` / `data class` / `inner class` etc. are matched
# via _MODS above, so `kind` is always the bare keyword `class`.

# Enum entries: `RED,` / `RED(0xff0000)` / `RED;` inside an `enum class` body.
# Kotlin has no `case` keyword; entries are just capitalised identifiers (by
# convention, not by the compiler) at the top of the body, ended by `;` or the
# closing brace.
ENUM_ENTRY_RE = re.compile(r"^(?P<indent>[ \t]*)(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*(?P<rest>[,;(].*)?$")

TYPE_KINDS = {"class", "interface", "object"}


@dataclass
class Symbol:
    kind: str
    name: str
    signature: str
    file: str
    line: int
    container: str = ""

    @property
    def qualified(self) -> str:
        return f"{self.container}.{self.name}" if self.container else self.name


def _name_from_rest(kind: str, rest: str) -> str:
    rest = rest.strip()
    m = re.match(r"[`]?([A-Za-z_][A-Za-z0-9_]*)[`]?", rest)
    return m.group(1) if m else rest[:40]


def _signature(kind: str, name: str, rest: str) -> str:
    """A compact, readable one-line rendering of the declaration."""
    rest = rest.strip()
    # Drop a trailing body brace / `= value` and anything after it, but keep a
    # single-expression function's return type by stopping at `{` or a
    # top-level ` = ` only when what follows looks like a body, not a default.
    brace = rest.find("{")
    if brace != -1:
        rest = rest[:brace].strip()
    rest = re.sub(r"\s+", " ", rest).rstrip()
    return f"{kind} {rest}" if rest else kind


def _strip_comments_and_strings(text: str) -> str:
    """Blank out string literals and comments so brace counting is reliable.

    Newlines are preserved so line numbers stay correct. Kotlin string
    templates (`"${'$'}{expr}"`) are not unpacked -- the whole string is
    blanked, which is safe since braces inside a template are balanced within
    the string and never affect scope depth outside it.
    """
    out = []
    i, n = 0, len(text)
    state = None  # None | 'line' | 'block' | 'str' | 'rawstr'
    depth = 0
    while i < n:
        c = text[i]
        nxt = text[i + 1] if i + 1 < n else ""
        nxt3 = text[i:i + 3]
        if state is None:
            if c == "/" and nxt == "/":
                state = "line"; out.append("  "); i += 2; continue
            if c == "/" and nxt == "*":
                state = "block"; depth = 1; out.append("  "); i += 2; continue
            if nxt3 == '"""':
                state = "rawstr"; out.append("   "); i += 3; continue
            if c == '"':
                state = "str"; out.append(" "); i += 1; continue
            out.append(c); i += 1; continue
        if state == "line":
            if c == "\n":
                state = None; out.append("\n")
            else:
                out.append(" ")
            i += 1; continue
        if state == "block":
            if c == "/" and nxt == "*":
                depth += 1; out.append("  "); i += 2; continue
            if c == "*" and nxt == "/":
                depth -= 1; out.append("  "); i += 2
                if depth == 0:
                    state = None
                continue
            out.append("\n" if c == "\n" else " "); i += 1; continue
        if state == "rawstr":
            if text[i:i + 3] == '"""':
                state = None; out.append("   "); i += 3; continue
            out.append("\n" if c == "\n" else " "); i += 1; continue
        # inside a regular string
        if c == "\\":
            out.append("  "); i += 2; continue
        if c == '"':
            state = None
        out.append("\n" if c == "\n" else " ")
        i += 1
    return "".join(out)


@dataclass
class Scope:
    """One open brace scope while walking a file."""
    depth: int          # brace depth at which this scope was opened
    name: str           # qualified type name, or "" for non-type scopes
    kind: str           # "class" | "interface" | "object" | "block" | "ctor"
    public: bool        # whether members declared here can be part of the public API
    is_enum: bool = False
    close_at_parens: int = -1  # for kind == "ctor": paren depth that closes this scope


def parse_file(path: str) -> list[Symbol]:
    """Extract every public declaration from one Kotlin file.

    Walks the file line by line tracking brace scopes. A top-level or member
    declaration counts as public when it is not `private`/`internal`/
    `protected` *and* every enclosing type scope is itself public -- a public
    fun inside a private class is not reachable and so is not part of the
    surface.
    """
    with open(path, "r", encoding="utf-8") as fh:
        raw = fh.read()
    lines = _strip_comments_and_strings(raw).split("\n")

    rel = os.path.relpath(path, REPO_ROOT)
    symbols: list[Symbol] = []
    stack: list[Scope] = []
    depth = 0
    paren_depth = 0

    for idx, line in enumerate(lines):
        opens = line.count("{") - line.count("}")
        paren_depth_before_line = paren_depth
        paren_depth += line.count("(") - line.count(")")

        if stack and stack[-1].kind == "ctor" and paren_depth <= stack[-1].close_at_parens:
            # The primary constructor's parameter list just balanced (e.g. the
            # `)` closing `class Completed(\n val x: Int\n)`). Its `val`/`var`
            # parameters were scanned as normal member declarations while this
            # scope was open, attributed to the class by `container()`. If a
            # `{` body follows on this same line, fall through so it still
            # gets handled below; otherwise the type has no body and this
            # scope is done.
            stack.pop()
            if opens <= 0:
                while stack and stack[-1].kind != "ctor" and depth <= stack[-1].depth:
                    stack.pop()
                continue

        def enclosing_public() -> bool:
            return all(sc.public for sc in stack if sc.kind != "block")

        def in_function_body() -> bool:
            # A `val`/`var`/`fun`/`class` written directly inside a function
            # body (the innermost scope is a "block") is a local declaration,
            # not a member -- Kotlin requires no keyword to shadow the
            # enclosing type's visibility here, unlike a member declaration.
            return bool(stack) and stack[-1].kind == "block"

        def container() -> str:
            for sc in reversed(stack):
                if sc.kind == "block":
                    return ""      # inside a function body: not a declaration site
                if sc.name:
                    return sc.name
            return ""

        # Enum entries have no keyword and no access modifier of their own;
        # only collect while directly inside a public `enum class` body.
        if stack and stack[-1].is_enum:
            em = ENUM_ENTRY_RE.match(line)
            if em and em.group("name") not in ("companion",):
                if stack[-1].public and enclosing_public():
                    symbols.append(
                        Symbol("entry", em.group("name"), f"entry {em.group('name')}",
                               rel, idx + 1, stack[-1].name)
                    )
                depth += opens
                while stack and stack[-1].kind != "ctor" and depth <= stack[-1].depth:
                    stack.pop()
                continue

        m = DECL_RE.match(line)
        if m:
            kind, rest = m.group("kind"), m.group("rest")
            access = m.group("access")
            mods = m.group("mods") or ""
            is_enum_class = "enum" in mods.split()
            is_data_class = "data" in mods.split()
            is_sealed = "sealed" in mods.split()

            # A function's parameter list may wrap across multiple lines; pull
            # in continuation lines until it balances so overloads are
            # distinguished by their full signature. A class's constructor
            # instead opens a `ctor` scope below, so its parameter lines are
            # scanned as ordinary member declarations rather than swallowed
            # into one blob -- that is what lets each `val`/`var` parameter
            # be recorded as its own property, correctly attributed.
            if kind == "fun":
                rest, _ = _join_declaration(lines, idx, rest)

            name = _name_from_rest(kind, rest)
            is_public = access not in NON_PUBLIC_MODS
            visible = enclosing_public() and is_public and not in_function_body()

            if kind in TYPE_KINDS:
                display_kind = kind
                if kind == "class" and is_enum_class:
                    display_kind = "enum"
                elif kind == "class" and is_data_class:
                    display_kind = "data class"
                elif kind == "class" and is_sealed:
                    display_kind = "sealed class"
                qualified = f"{container()}.{name}" if container() else name
                if visible:
                    symbols.append(
                        Symbol(display_kind, name, _signature(display_kind, name, rest), rel, idx + 1, container())
                    )
                # A primary constructor's parameter list may still be open
                # (`class Foo(\n  val x: Int\n)`); push a scope for it now so
                # its `val`/`var` parameters, scanned on the following lines,
                # are attributed to this type rather than its enclosing one.
                ctor_open = "(" in rest and paren_depth > paren_depth_before_line
                if ctor_open:
                    stack.append(Scope(depth, qualified, "ctor", visible,
                                        close_at_parens=paren_depth_before_line))
                if opens > 0:
                    stack.append(Scope(depth, qualified, kind, visible, is_enum=is_enum_class))
                    depth += opens
                    continue
                if ctor_open:
                    continue
            else:
                if visible:
                    symbols.append(
                        Symbol(kind, name, _signature(kind, name, rest), rel, idx + 1, container())
                    )
                if opens > 0:
                    stack.append(Scope(depth, "", "block", visible))
                    depth += opens
                    continue
            depth += opens
            while stack and stack[-1].kind != "ctor" and depth <= stack[-1].depth:
                stack.pop()
            continue

        # Non-matching scope openers (companion object, init {}, if/when/etc.)
        # still have to be tracked, or their contents would be misattributed
        # to the enclosing public type.
        if opens > 0:
            comp = re.match(r"^[ \t]*companion object\b", line)
            if comp:
                # A companion object's public members are reachable as
                # `Type.member`, so it does not restrict visibility further
                # than its enclosing type already does.
                stack.append(Scope(depth, container(), "object", enclosing_public()))
            else:
                stack.append(Scope(depth, "", "block", stack[-1].public if stack else True))

        depth += opens
        while stack and stack[-1].kind != "ctor" and depth <= stack[-1].depth:
            stack.pop()

    return symbols


def _join_declaration(lines: list[str], idx: int, rest: str, max_lookahead: int = 40) -> tuple[str, int]:
    """Append continuation lines until the declaration's parentheses balance.

    Returns the joined text and the index of the last line folded in, so the
    caller can skip re-scanning those lines (their `val`/`var` parameters
    would otherwise be misattributed to the wrong enclosing scope) and can
    account for any braces they opened or closed.
    """
    if "(" not in rest:
        return rest, idx
    depth = rest.count("(") - rest.count(")")
    if depth <= 0:
        return rest, idx
    parts = [rest.rstrip()]
    last = idx
    for j in range(idx + 1, min(idx + 1 + max_lookahead, len(lines))):
        nxt = lines[j]
        parts.append(nxt.strip())
        last = j
        depth += nxt.count("(") - nxt.count(")")
        if depth <= 0:
            break
    return " ".join(p for p in parts if p), last


def collect() -> list[Symbol]:
    out: list[Symbol] = []
    for module in MODULES:
        src = os.path.join(REPO_ROOT, module, "src", "main", "java")
        if not os.path.isdir(src):
            continue
        for dirpath, _dirnames, filenames in os.walk(src):
            for fn in sorted(filenames):
                if fn.endswith(".kt"):
                    out.extend(parse_file(os.path.join(dirpath, fn)))
    return out


MODULE_BLURB = {
    "FrameSDK": "Core SDK: networking for every Frame API resource, account events, "
                "Sonar fraud sessions, Fingerprint device identification, Evervault "
                "card encryption.",
    "FrameSDK-UI": "Checkout and cart UI: Compose and XML views, theming, validation, "
                   "Google Pay, shared reusable components (payment method rows, "
                   "card brand art).",
    "FrameSDK-Onboarding": "Onboarding product: the capability-driven identity/payment "
                           "verification flow, its screens, and the onboarding-only "
                           "APIs (3DS, IDV, phone OTP, geocompliance, Plaid, Persona).",
}

KIND_ORDER = ["class", "data class", "sealed class", "enum", "interface", "object",
              "typealias", "fun", "val", "var", "entry"]
KIND_LABEL = {
    "class": "Classes", "data class": "Data classes", "sealed class": "Sealed classes",
    "enum": "Enums", "interface": "Interfaces", "object": "Objects",
    "typealias": "Type aliases", "fun": "Functions", "val": "Properties (val)",
    "var": "Properties (var)", "entry": "Enum entries",
}


def _module_of(rel_path: str) -> str:
    parts = rel_path.split(os.sep)
    return parts[0] if parts and parts[0] in MODULES else "FrameSDK"


def _group_path(rel_path: str) -> str:
    """The package directory a file sits in, relative to its module's java root."""
    parts = rel_path.split(os.sep)
    try:
        java_idx = parts.index("java")
    except ValueError:
        return "(root)"
    dir_parts = parts[java_idx + 1:-1]
    return "/".join(dir_parts) if dir_parts else "(root)"


def render(symbols: list[Symbol]) -> str:
    """Render the autogenerated portion of the map."""
    total = len(symbols)
    by_module: dict[str, list[Symbol]] = {}
    for s in symbols:
        by_module.setdefault(_module_of(s.file), []).append(s)

    kind_counts = {}
    for s in symbols:
        kind_counts[s.kind] = kind_counts.get(s.kind, 0) + 1

    out: list[str] = []
    w = out.append

    w(BEGIN)
    w("")
    w("<!-- Generated by scripts/generate_sdk_map.py. Do not edit by hand: this")
    w("     section is rebuilt from source on every push. Add commentary in the")
    w("     hand-written sections outside the AUTOGENERATED markers instead. -->")
    w("")
    w("## Public API inventory")
    w("")
    w(f"**{total} public symbols** across "
      f"{len({s.file for s in symbols})} files in {len(by_module)} modules.")
    w("")
    w("| Kind | Count |")
    w("|------|-------|")
    for k in KIND_ORDER:
        if kind_counts.get(k):
            w(f"| {KIND_LABEL[k]} | {kind_counts[k]} |")
    w(f"| **Total** | **{total}** |")
    w("")

    for module in MODULES:
        if module not in by_module:
            continue
        syms = by_module[module]
        w(f"### `{module}` — {len(syms)} public symbols")
        w("")
        if module in MODULE_BLURB:
            w(MODULE_BLURB[module])
            w("")

        groups: dict[str, list[Symbol]] = {}
        for s in syms:
            groups.setdefault(_group_path(s.file), []).append(s)

        for group in sorted(groups):
            gsyms = groups[group]
            w(f"#### {group} ({len(gsyms)})")
            w("")
            by_file: dict[str, list[Symbol]] = {}
            for s in gsyms:
                by_file.setdefault(s.file, []).append(s)
            for fpath in sorted(by_file):
                fsyms = sorted(by_file[fpath], key=lambda s: s.line)
                w(f"<details><summary><code>{os.path.basename(fpath)}</code> "
                  f"— {len(fsyms)} symbols</summary>")
                w("")
                w(f"[`{fpath}`]({_link(fpath)})")
                w("")
                w("| Symbol | Kind | Declaration | Line |")
                w("|--------|------|-------------|------|")
                for s in fsyms:
                    w(f"| `{_md(s.qualified)}` | {s.kind} | `{_md(_trunc(s.signature))}` "
                      f"| [{s.line}]({_link(fpath)}#L{s.line}) |")
                w("")
                w("</details>")
                w("")
    w(END)
    return "\n".join(out)


def _link(rel_path: str) -> str:
    return rel_path.replace(os.sep, "/")


def _md(text: str) -> str:
    """Escape the characters that would break a markdown table cell."""
    return text.replace("|", "\\|")


def _trunc(sig: str, limit: int = 160) -> str:
    sig = sig.strip()
    return sig if len(sig) <= limit else sig[: limit - 1] + "…"


TEMPLATE = """# Frame Android SDK Map

A complete map of the public surface of the Frame Android SDK: every public
class, interface, object, function, property, and enum entry across the three
library modules.

The inventory below is **generated from source** by `scripts/generate_sdk_map.py`
and refreshed automatically by `.github/workflows/sdk-map.yml` on every push that
touches a module's `src/main/java`. If you add or remove a public symbol, the
map updates itself — there is nothing to keep in sync by hand.

Prose written outside the `AUTOGENERATED` markers is preserved across
regeneration, so architectural notes belong there.

## Module layout

| Module | Purpose |
|--------|---------|
| `FrameSDK` | Core networking for every Frame API resource, account events, Sonar fraud sessions, Fingerprint identification, Evervault card encryption. |
| `FrameSDK-UI` | Checkout/cart UI: Compose and XML views, theming, validation, Google Pay. |
| `FrameSDK-Onboarding` | Capability-driven onboarding flow, its screens, and onboarding-only APIs (3DS, IDV, phone OTP, geocompliance, Plaid, Persona). |

Dependency direction: `FrameSDK-Onboarding` → `FrameSDK-UI` → `FrameSDK`. The
reverse is never true.

## How to read the inventory

- Symbols are grouped by module, then by package directory, then by file.
- `Symbol` is the qualified name — `FrameObjects.Capabilities` means the type
  is nested inside (or a member of) `FrameObjects`.
- Kotlin declarations are public by default; a declaration counts as part of
  the surface unless it (or an enclosing class/object/interface) is marked
  `internal`, `private`, or `protected`.
- Members declared inside a non-public type are excluded: they are not
  reachable by an integrator even when the member itself carries no modifier.
- Overloads are listed separately and distinguished by their full signature.

"""


def build_document(symbols: list[Symbol], previous: str | None) -> str:
    """Compose the full map, preserving any hand-written prose."""
    generated = render(symbols)
    if previous and BEGIN in previous and END in previous:
        head = previous[: previous.index(BEGIN)]
        tail = previous[previous.index(END) + len(END):]
        return head + generated + tail
    return TEMPLATE + generated + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the map is out of date; do not write")
    args = ap.parse_args()

    symbols = collect()
    symbols.sort(key=lambda s: (s.file, s.line, s.qualified))

    previous = None
    if os.path.exists(MAP_PATH):
        with open(MAP_PATH, "r", encoding="utf-8") as fh:
            previous = fh.read()

    document = build_document(symbols, previous)

    if args.check:
        if previous == document:
            print(f"✅ SDK map is up to date ({len(symbols)} public symbols).")
            return 0
        print("❌ SDK map is out of date. Run: python3 scripts/generate_sdk_map.py")
        if previous is not None:
            _print_symbol_diff(previous, document)
        return 1

    with open(MAP_PATH, "w", encoding="utf-8") as fh:
        fh.write(document)
    changed = previous != document
    status = "updated" if changed else "unchanged"
    print(f"{'✏️' if changed else '✅'} SDK_MAP.md {status} "
          f"({len(symbols)} public symbols).")
    return 0


# Symbol | Kind | Declaration — the declaration is part of the identity so that
# overloads are distinct entries. Without it, removing one overload would
# leave the other's name in the set and the diff would report no change.
# The kind group allows an internal space ("data class", "sealed class").
_ROW_RE = re.compile(r"^\| `([^`]+)` \| ([\w ]+?) \| `(.*)` \|")


def _symbol_rows(document: str) -> set[str]:
    rows = set()
    for line in document.split("\n"):
        m = _ROW_RE.match(line)
        if m:
            rows.add(f"{m.group(2)} {m.group(1)}  {m.group(3)}")
    return rows


def _fmt_row(row: str, limit: int = 110) -> str:
    """Collapse a row key to one readable line for the console diff."""
    row = re.sub(r"\s+", " ", row).strip()
    return row if len(row) <= limit else row[: limit - 1] + "…"


def _print_symbol_diff(previous: str, current: str) -> None:
    """Show which symbols changed, so the failure is actionable on its own."""
    before, after = _symbol_rows(previous), _symbol_rows(current)
    added, removed = sorted(after - before), sorted(before - after)
    if added:
        print(f"\n  Added ({len(added)}):")
        for a in added[:40]:
            print(f"    + {_fmt_row(a)}")
        if len(added) > 40:
            print(f"    … and {len(added) - 40} more")
    if removed:
        print(f"\n  Removed ({len(removed)}):")
        for r in removed[:40]:
            print(f"    - {_fmt_row(r)}")
        if len(removed) > 40:
            print(f"    … and {len(removed) - 40} more")
    if not added and not removed:
        print("\n  (Symbol set unchanged; formatting or line numbers moved.)")


if __name__ == "__main__":
    sys.exit(main())
