package com.framepayments.framesdk_ui.viewmodels

sealed class AvailableCountry(val alpha2Code: String, val displayName: String) {
    object AF : AvailableCountry("AF", "Afghanistan")
    object AX : AvailableCountry("AX", "Åland Islands")
    object AL : AvailableCountry("AL", "Albania")
    object DZ : AvailableCountry("DZ", "Algeria")
    object AS : AvailableCountry("AS", "American Samoa")
    object AD : AvailableCountry("AD", "Andorra")
    object AO : AvailableCountry("AO", "Angola")
    object AI : AvailableCountry("AI", "Anguilla")
    object AQ : AvailableCountry("AQ", "Antarctica")
    object AG : AvailableCountry("AG", "Antigua and Barbuda")
    object AR : AvailableCountry("AR", "Argentina")
    object AM : AvailableCountry("AM", "Armenia")
    object AW : AvailableCountry("AW", "Aruba")
    object AU : AvailableCountry("AU", "Australia")
    object AT : AvailableCountry("AT", "Austria")
    object AZ : AvailableCountry("AZ", "Azerbaijan")
    object BS : AvailableCountry("BS", "Bahamas")
    object BH : AvailableCountry("BH", "Bahrain")
    object BD : AvailableCountry("BD", "Bangladesh")
    object BB : AvailableCountry("BB", "Barbados")
    object BY : AvailableCountry("BY", "Belarus")
    object BE : AvailableCountry("BE", "Belgium")
    object BZ : AvailableCountry("BZ", "Belize")
    object BJ : AvailableCountry("BJ", "Benin")
    object BM : AvailableCountry("BM", "Bermuda")
    object BT : AvailableCountry("BT", "Bhutan")
    object BO : AvailableCountry("BO", "Bolivia")
    object BQ : AvailableCountry("BQ", "Bonaire, Sint Eustatius and Saba")
    object BA : AvailableCountry("BA", "Bosnia and Herzegovina")
    object BW : AvailableCountry("BW", "Botswana")
    object BV : AvailableCountry("BV", "Bouvet Island")
    object BR : AvailableCountry("BR", "Brazil")
    object IO : AvailableCountry("IO", "British Indian Ocean Territory")
    object BN : AvailableCountry("BN", "Brunei Darussalam")
    object BG : AvailableCountry("BG", "Bulgaria")
    object BF : AvailableCountry("BF", "Burkina Faso")
    object BI : AvailableCountry("BI", "Burundi")
    object KH : AvailableCountry("KH", "Cambodia")
    object CM : AvailableCountry("CM", "Cameroon")
    object CA : AvailableCountry("CA", "Canada")
    object CV : AvailableCountry("CV", "Cape Verde")
    object KY : AvailableCountry("KY", "Cayman Islands")
    object CF : AvailableCountry("CF", "Central African Republic")
    object TD : AvailableCountry("TD", "Chad")
    object CL : AvailableCountry("CL", "Chile")
    object CN : AvailableCountry("CN", "China")
    object CX : AvailableCountry("CX", "Christmas Island")
    object CC : AvailableCountry("CC", "Cocos (Keeling) Islands")
    object CO : AvailableCountry("CO", "Colombia")
    object KM : AvailableCountry("KM", "Comoros")
    object CG : AvailableCountry("CG", "Congo")
    object CD : AvailableCountry("CD", "Congo, Democratic Republic of the")
    object CK : AvailableCountry("CK", "Cook Islands")
    object CR : AvailableCountry("CR", "Costa Rica")
    object CI : AvailableCountry("CI", "Côte d'Ivoire")
    object HR : AvailableCountry("HR", "Croatia")
    object CU : AvailableCountry("CU", "Cuba")
    object CW : AvailableCountry("CW", "Curaçao")
    object CY : AvailableCountry("CY", "Cyprus")
    object CZ : AvailableCountry("CZ", "Czech Republic")
    object DK : AvailableCountry("DK", "Denmark")
    object DJ : AvailableCountry("DJ", "Djibouti")
    object DM : AvailableCountry("DM", "Dominica")
    object DO : AvailableCountry("DO", "Dominican Republic")
    object EC : AvailableCountry("EC", "Ecuador")
    object EG : AvailableCountry("EG", "Egypt")
    object SV : AvailableCountry("SV", "El Salvador")
    object GQ : AvailableCountry("GQ", "Equatorial Guinea")
    object ER : AvailableCountry("ER", "Eritrea")
    object EE : AvailableCountry("EE", "Estonia")
    object SZ : AvailableCountry("SZ", "Eswatini")
    object ET : AvailableCountry("ET", "Ethiopia")
    object FK : AvailableCountry("FK", "Falkland Islands (Malvinas)")
    object FO : AvailableCountry("FO", "Faroe Islands")
    object FJ : AvailableCountry("FJ", "Fiji")
    object FI : AvailableCountry("FI", "Finland")
    object FR : AvailableCountry("FR", "France")
    object GF : AvailableCountry("GF", "French Guiana")
    object PF : AvailableCountry("PF", "French Polynesia")
    object TF : AvailableCountry("TF", "French Southern Territories")
    object GA : AvailableCountry("GA", "Gabon")
    object GM : AvailableCountry("GM", "Gambia")
    object GE : AvailableCountry("GE", "Georgia")
    object DE : AvailableCountry("DE", "Germany")
    object GH : AvailableCountry("GH", "Ghana")
    object GI : AvailableCountry("GI", "Gibraltar")
    object GR : AvailableCountry("GR", "Greece")
    object GL : AvailableCountry("GL", "Greenland")
    object GD : AvailableCountry("GD", "Grenada")
    object GP : AvailableCountry("GP", "Guadeloupe")
    object GU : AvailableCountry("GU", "Guam")
    object GT : AvailableCountry("GT", "Guatemala")
    object GG : AvailableCountry("GG", "Guernsey")
    object GN : AvailableCountry("GN", "Guinea")
    object GW : AvailableCountry("GW", "Guinea-Bissau")
    object GY : AvailableCountry("GY", "Guyana")
    object HT : AvailableCountry("HT", "Haiti")
    object HM : AvailableCountry("HM", "Heard Island and McDonald Islands")
    object VA : AvailableCountry("VA", "Holy See")
    object HN : AvailableCountry("HN", "Honduras")
    object HK : AvailableCountry("HK", "Hong Kong")
    object HU : AvailableCountry("HU", "Hungary")
    object IS : AvailableCountry("IS", "Iceland")
    object IN : AvailableCountry("IN", "India")
    object ID : AvailableCountry("ID", "Indonesia")
    object IR : AvailableCountry("IR", "Iran")
    object IQ : AvailableCountry("IQ", "Iraq")
    object IE : AvailableCountry("IE", "Ireland")
    object IM : AvailableCountry("IM", "Isle of Man")
    object IL : AvailableCountry("IL", "Israel")
    object IT : AvailableCountry("IT", "Italy")
    object JM : AvailableCountry("JM", "Jamaica")
    object JP : AvailableCountry("JP", "Japan")
    object JE : AvailableCountry("JE", "Jersey")
    object JO : AvailableCountry("JO", "Jordan")
    object KZ : AvailableCountry("KZ", "Kazakhstan")
    object KE : AvailableCountry("KE", "Kenya")
    object KI : AvailableCountry("KI", "Kiribati")
    object KP : AvailableCountry("KP", "Korea, Democratic People's Republic of")
    object KR : AvailableCountry("KR", "Korea, Republic of")
    object KW : AvailableCountry("KW", "Kuwait")
    object KG : AvailableCountry("KG", "Kyrgyzstan")
    object LA : AvailableCountry("LA", "Lao People's Democratic Republic")
    object LV : AvailableCountry("LV", "Latvia")
    object LB : AvailableCountry("LB", "Lebanon")
    object LS : AvailableCountry("LS", "Lesotho")
    object LR : AvailableCountry("LR", "Liberia")
    object LY : AvailableCountry("LY", "Libya")
    object LI : AvailableCountry("LI", "Liechtenstein")
    object LT : AvailableCountry("LT", "Lithuania")
    object LU : AvailableCountry("LU", "Luxembourg")
    object MO : AvailableCountry("MO", "Macao")
    object MG : AvailableCountry("MG", "Madagascar")
    object MW : AvailableCountry("MW", "Malawi")
    object MY : AvailableCountry("MY", "Malaysia")
    object MV : AvailableCountry("MV", "Maldives")
    object ML : AvailableCountry("ML", "Mali")
    object MT : AvailableCountry("MT", "Malta")
    object MH : AvailableCountry("MH", "Marshall Islands")
    object MQ : AvailableCountry("MQ", "Martinique")
    object MR : AvailableCountry("MR", "Mauritania")
    object MU : AvailableCountry("MU", "Mauritius")
    object YT : AvailableCountry("YT", "Mayotte")
    object MX : AvailableCountry("MX", "Mexico")
    object FM : AvailableCountry("FM", "Micronesia (Federated States of)")
    object MD : AvailableCountry("MD", "Moldova")
    object MC : AvailableCountry("MC", "Monaco")
    object MN : AvailableCountry("MN", "Mongolia")
    object ME : AvailableCountry("ME", "Montenegro")
    object MS : AvailableCountry("MS", "Montserrat")
    object MA : AvailableCountry("MA", "Morocco")
    object MZ : AvailableCountry("MZ", "Mozambique")
    object MM : AvailableCountry("MM", "Myanmar")
    object NA : AvailableCountry("NA", "Namibia")
    object NR : AvailableCountry("NR", "Nauru")
    object NP : AvailableCountry("NP", "Nepal")
    object NL : AvailableCountry("NL", "Netherlands")
    object NC : AvailableCountry("NC", "New Caledonia")
    object NZ : AvailableCountry("NZ", "New Zealand")
    object NI : AvailableCountry("NI", "Nicaragua")
    object NE : AvailableCountry("NE", "Niger")
    object NG : AvailableCountry("NG", "Nigeria")
    object NU : AvailableCountry("NU", "Niue")
    object NF : AvailableCountry("NF", "Norfolk Island")
    object MK : AvailableCountry("MK", "North Macedonia")
    object MP : AvailableCountry("MP", "Northern Mariana Islands")
    object NO : AvailableCountry("NO", "Norway")
    object OM : AvailableCountry("OM", "Oman")
    object PK : AvailableCountry("PK", "Pakistan")
    object PW : AvailableCountry("PW", "Palau")
    object PS : AvailableCountry("PS", "Palestine, State of")
    object PA : AvailableCountry("PA", "Panama")
    object PG : AvailableCountry("PG", "Papua New Guinea")
    object PY : AvailableCountry("PY", "Paraguay")
    object PE : AvailableCountry("PE", "Peru")
    object PH : AvailableCountry("PH", "Philippines")
    object PN : AvailableCountry("PN", "Pitcairn")
    object PL : AvailableCountry("PL", "Poland")
    object PT : AvailableCountry("PT", "Portugal")
    object PR : AvailableCountry("PR", "Puerto Rico")
    object QA : AvailableCountry("QA", "Qatar")
    object RE : AvailableCountry("RE", "Réunion")
    object RO : AvailableCountry("RO", "Romania")
    object RU : AvailableCountry("RU", "Russian Federation")
    object RW : AvailableCountry("RW", "Rwanda")
    object BL : AvailableCountry("BL", "Saint Barthélemy")
    object SH : AvailableCountry("SH", "Saint Helena, Ascension and Tristan da Cunha")
    object KN : AvailableCountry("KN", "Saint Kitts and Nevis")
    object LC : AvailableCountry("LC", "Saint Lucia")
    object MF : AvailableCountry("MF", "Saint Martin (French part)")
    object PM : AvailableCountry("PM", "Saint Pierre and Miquelon")
    object VC : AvailableCountry("VC", "Saint Vincent and the Grenadines")
    object WS : AvailableCountry("WS", "Samoa")
    object SM : AvailableCountry("SM", "San Marino")
    object ST : AvailableCountry("ST", "Sao Tome and Principe")
    object SA : AvailableCountry("SA", "Saudi Arabia")
    object SN : AvailableCountry("SN", "Senegal")
    object RS : AvailableCountry("RS", "Serbia")
    object SC : AvailableCountry("SC", "Seychelles")
    object SL : AvailableCountry("SL", "Sierra Leone")
    object SG : AvailableCountry("SG", "Singapore")
    object SX : AvailableCountry("SX", "Sint Maarten (Dutch part)")
    object SK : AvailableCountry("SK", "Slovakia")
    object SI : AvailableCountry("SI", "Slovenia")
    object SB : AvailableCountry("SB", "Solomon Islands")
    object SO : AvailableCountry("SO", "Somalia")
    object ZA : AvailableCountry("ZA", "South Africa")
    object GS : AvailableCountry("GS", "South Georgia and the South Sandwich Islands")
    object SS : AvailableCountry("SS", "South Sudan")
    object ES : AvailableCountry("ES", "Spain")
    object LK : AvailableCountry("LK", "Sri Lanka")
    object SD : AvailableCountry("SD", "Sudan")
    object SR : AvailableCountry("SR", "Suriname")
    object SJ : AvailableCountry("SJ", "Svalbard and Jan Mayen")
    object SE : AvailableCountry("SE", "Sweden")
    object CH : AvailableCountry("CH", "Switzerland")
    object SY : AvailableCountry("SY", "Syrian Arab Republic")
    object TW : AvailableCountry("TW", "Taiwan")
    object TJ : AvailableCountry("TJ", "Tajikistan")
    object TZ : AvailableCountry("TZ", "Tanzania")
    object TH : AvailableCountry("TH", "Thailand")
    object TL : AvailableCountry("TL", "Timor-Leste")
    object TG : AvailableCountry("TG", "Togo")
    object TK : AvailableCountry("TK", "Tokelau")
    object TO : AvailableCountry("TO", "Tonga")
    object TT : AvailableCountry("TT", "Trinidad and Tobago")
    object TN : AvailableCountry("TN", "Tunisia")
    object TR : AvailableCountry("TR", "Turkey")
    object TM : AvailableCountry("TM", "Turkmenistan")
    object TC : AvailableCountry("TC", "Turks and Caicos Islands")
    object TV : AvailableCountry("TV", "Tuvalu")
    object UG : AvailableCountry("UG", "Uganda")
    object UA : AvailableCountry("UA", "Ukraine")
    object AE : AvailableCountry("AE", "United Arab Emirates")
    object GB : AvailableCountry("GB", "United Kingdom")
    object US : AvailableCountry("US", "United States")
    object UM : AvailableCountry("UM", "United States Minor Outlying Islands")
    object UY : AvailableCountry("UY", "Uruguay")
    object UZ : AvailableCountry("UZ", "Uzbekistan")
    object VU : AvailableCountry("VU", "Vanuatu")
    object VE : AvailableCountry("VE", "Venezuela")
    object VN : AvailableCountry("VN", "Viet Nam")
    object VG : AvailableCountry("VG", "Virgin Islands, British")
    object VI : AvailableCountry("VI", "Virgin Islands, U.S.")
    object WF : AvailableCountry("WF", "Wallis and Futuna")
    object EH : AvailableCountry("EH", "Western Sahara")
    object YE : AvailableCountry("YE", "Yemen")
    object ZM : AvailableCountry("ZM", "Zambia")
    object ZW : AvailableCountry("ZW", "Zimbabwe")

    companion object {
        val allCountries: List<AvailableCountry> = listOf(
            AF, AX, AL, DZ, AS, AD, AO, AI, AQ, AG,
            AR, AM, AW, AU, AT, AZ, BS, BH, BD, BB,
            BY, BE, BZ, BJ, BM, BT, BO, BQ, BA, BW,
            BV, BR, IO, BN, BG, BF, BI, KH, CM, CA,
            CV, KY, CF, TD, CL, CN, CX, CC, CO, KM,
            CG, CD, CK, CR, CI, HR, CU, CW, CY, CZ,
            DK, DJ, DM, DO, EC, EG, SV, GQ, ER, EE,
            SZ, ET, FK, FO, FJ, FI, FR, GF, PF, TF,
            GA, GM, GE, DE, GH, GI, GR, GL, GD, GP,
            GU, GT, GG, GN, GW, GY, HT, HM, VA, HN,
            HK, HU, IS, IN, ID, IR, IQ, IE, IM, IL,
            IT, JM, JP, JE, JO, KZ, KE, KI, KP, KR,
            KW, KG, LA, LV, LB, LS, LR, LY, LI, LT,
            LU, MO, MG, MW, MY, MV, ML, MT, MH, MQ,
            MR, MU, YT, MX, FM, MD, MC, MN, ME, MS,
            MA, MZ, MM, NA, NR, NP, NL, NC, NZ, NI,
            NE, NG, NU, NF, MK, MP, NO, OM, PK, PW,
            PS, PA, PG, PY, PE, PH, PN, PL, PT, PR,
            QA, RE, RO, RU, RW, BL, SH, KN, LC, MF,
            PM, VC, WS, SM, ST, SA, SN, RS, SC, SL,
            SG, SX, SK, SI, SB, SO, ZA, GS, SS, ES,
            LK, SD, SR, SJ, SE, CH, SY, TW, TJ, TZ,
            TH, TL, TG, TK, TO, TT, TN, TR, TM, TC,
            TV, UG, UA, AE, GB, US, UM, UY, UZ, VU,
            VE, VN, VG, VI, WF, EH, YE, ZM, ZW
        )
    }
}